site_name: SIENTIA™ Log Library
site_url: https://www.aignosi.ai/
baseurl: /documentation/sientia-log-library  # This is the key part

nav:
  - Home: 
    - Introduction: index.md
  - Modules:  
      - Basic Tracker : basic.md
      - Simple Tracker : simple.md
      - Regression Tracker: regression.md
  - Quick Start:
      - Simple Tracker Notebook: simple_tracker.ipynb
      - Regression Tracker Notebook: regression_tracker.ipynb

plugins: 
  - mkdocstrings
  - mkdocs-jupyter

use_directory_urls: false
theme: readthedocs
