name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: '3.x'
      - uses: actions/cache@v2
        with:
            key: ${{ github.ref }}
            path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings[python]
      - run: pip install mkdocs-jupyter
      
      - run: mkdocs gh-deploy --force

        # Add the CNAME file with your custom domain after deployment
      - name: Add CNAME file for custom domain
        run: |
          touch CNAME
          echo "www.aignosi.ai" > CNAME  # Replace with your custom domain
          cd site  # Navigate to the 'site' directory
          git add CNAME
          git commit -m "Add CNAME file for custom domain"
          git push origin gh-pages
